# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: SelfHostedPool
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'DockerHub'
        repository: 'ahmedavid/webapi'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(tag)
- stage: Provision
  displayName: "Provision Azure"
  dependsOn: Build
  jobs:
  - job: Provision
    displayName: "Provisining Container Instance"
    pool:
      name: SelfHostedPool
    variables: 
    - group: AzureServicePrinciple
    steps:
    - script: | 
        set -e
        terraform init -input=false
        terraform apply -input=false --auto-approve
      name: "RunTerraform"
      displayName: "RunTerraform"
      env:
        ARM_CLIENT_ID: $(ARM_CLIENT_ID)
        ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
        ARM_TENANT_ID: $(ARM_TENANT_ID)
        ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
        TF_VAR_imagebuild: $(tag)